### ISSUE TITLE
Serve `schemas.exasol.com` using a custom subdomain for GitHub pages

### ISSUE THREAD

**Issue by Nicoretti** [exasol/schemas#28]
## Summary

Serve `schemas.exasol.com`  via GitHub pages.

### Related
* #27 

### Requires
* #25 

### References
* https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site
* https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/about-custom-domains-and-github-pages

**Comment by redcatbear** [comment]
Shelved.
